[package]
name = "koebot"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = "0.10"
tokio = { version = "1", features = ["full"] }
url = "2"
tempfile = "3"
songbird = "0.2"
unicode-prettytable = "0.3.1"
