[package]
name = "koebot"
version = "0.1.0"
edition = "2018"

[dependencies]
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
tokio = { version = "1", features = ["full"] }
url = "2"
tempfile = "3"
songbird = "0.2"
unicode-prettytable = { git = "https://github.com/euank/unicode-prettytable", rev = "ef7039b4e1e19ab4da1bb7aed86721e974e77ef7" }
anyhow = "*"
uuid = "*"
log = "*"
env_logger = "*"
futures = "*"
